### ISSUE TITLE
Вот это ты верстаешь, а не делаешь картинками

### ISSUE THREAD

**Issue by vladkaryakin** [Jka4/mobile_app_landingPage#10]
https://github.com/Jka4/mobile_app_landingPage/blob/7de0e0030ee45bdcd5fac9f07fbbb708eb102121/src/index.html#L44-L61

Еще раз будет такое название классов , работы принимать не буду. Надеюсь, ты меня понял

**Comment by Jka4** [comment]
йо, забыл это убрать ))
Очень долго сидел над этими элементами чтобы нормально отображались на деск и на моб

**Comment by Jka4** [comment]
Я легко мог сделать это версткой, только зачем ?)
Там ведь из интерактивного только свитч

**Comment by vladkaryakin** [comment]
Ну вот сделай версткой

**Comment by Jka4** [comment]
Окс

**Comment by Jka4** [comment]
переделал
