### ISSUE TITLE
it should be a heading instead of div

### ISSUE THREAD

**Issue by vladkaryakin** [Jka4/mobile_app_landingPage#12]
https://github.com/Jka4/mobile_app_landingPage/blob/7de0e0030ee45bdcd5fac9f07fbbb708eb102121/src/index.html#L69
https://github.com/Jka4/mobile_app_landingPage/blob/7de0e0030ee45bdcd5fac9f07fbbb708eb102121/src/index.html#L84

**Comment by Jka4** [comment]
Исправил
