### ISSUE TITLE
Recheck the width of your block

### ISSUE THREAD

**Issue by vladkaryakin** [Jka4/mobile_app_landingPage#3]
http://joxi.ru/p270XxqiKkRlxA - макет
http://joxi.ru/DmBwMGocJlOV72 - твой страничка

Элементы вылезают за экран

**Comment by Jka4** [comment]
На каком это разрешении ?

По макетам там на 1440, и вроде все ок
![image](https://user-images.githubusercontent.com/45815145/60668642-22940900-9e75-11e9-9920-065467761c01.png)

**Comment by vladkaryakin** [comment]
Все гуд
